version: 2
updates:
- package-ecosystem: "docker"
  directories:
    - "/Containers/ami-bot"
  schedule:
    interval: "daily"
    time: "04:00"
  open-pull-requests-limit: 10
  rebase-strategy: "disabled"
  labels:
  - 3. to review
  - dependencies
  ignore:
    - dependency-name: "postgres"
      update-types: ["version-update:semver-major"]
    - dependency-name: "redis"
      update-types: ["version-update:semver-major"]