blank_issues_enabled: false
contact_links:
    - name: 📘 Documentation
      url: https://github.com/miel-R/nextcloud-stock-customs#readme
      about: Please read the docs first before submitting any report or request!
    - name: ⛑️ Questions and support (Nextcloud itself)
      url: https://help.nextcloud.com/
      about: For questions, support and help with Nextcloud - not this repository's compose stack
    - name: 💡 Suggest a new feature or discuss one
      url: https://help.nextcloud.com/
      about: For feature requests and discussion
    - name: 💼 Nextcloud Enterprise
      url: https://portal.nextcloud.com/
      about: If you are a Nextcloud Enterprise customer, or need Professional support, so it can be resolved directly by our dedicated engineers more quickly